"""add_meal_plans_and_logs

Revision ID: 361a65dd6b8b
Revises: cb0a44de2534
Create Date: 2026-03-25 09:43:30.366220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '361a65dd6b8b'
down_revision: Union[str, None] = 'cb0a44de2534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plans',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_table('day_plans',
    sa.Column('day_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('is_sport_day', sa.Boolean(), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein', sa.Float(), nullable=True),
    sa.Column('total_carbs', sa.Float(), nullable=True),
    sa.Column('total_fat', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('day_id')
    )
    op.create_table('meals',
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('day_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('prep_time_min', sa.Integer(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('sauce', sa.JSON(), nullable=True),
    sa.Column('plating_tip', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day_plans.day_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.create_table('meal_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=True),
    sa.Column('calories_consumed', sa.Float(), nullable=True),
    sa.Column('protein_consumed', sa.Float(), nullable=True),
    sa.Column('carbs_consumed', sa.Float(), nullable=True),
    sa.Column('fat_consumed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.meal_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_meal_logs_user_id'), 'meal_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_logs_user_id'), table_name='meal_logs')
    op.drop_table('meal_logs')
    op.drop_table('meals')
    op.drop_table('day_plans')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    # ### end Alembic commands ###
