"""sprint2_tiktok_recipes_admin

Revision ID: 4f5e171c60f1
Revises: b1e4f7a2c309
Create Date: 2026-03-26 11:42:20.013637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4f5e171c60f1'
down_revision: Union[str, None] = 'b1e4f7a2c309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_saves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_recipe_save')
    )
    op.create_index(op.f('ix_recipe_saves_user_id'), 'recipe_saves', ['user_id'], unique=False)
    op.add_column('recipes', sa.Column('tiktok_video_id', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('creator_handle', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('creator_name', sa.String(length=200), nullable=True))
    op.add_column('recipes', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    op.add_column('recipes', sa.Column('plating_tip', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('likes_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('recipes', sa.Column('saves_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('recipes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('recipes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('recipes', 'ingredients',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('recipes', 'steps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('recipes', 'image_urls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_profiles', 'qualitative_goals',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('user_profiles', 'sport_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('user_profiles', 'allergies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'allergies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('user_profiles', 'sport_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('user_profiles', 'qualitative_goals',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('recipes', 'image_urls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('recipes', 'steps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('recipes', 'ingredients',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('recipes', 'updated_at')
    op.drop_column('recipes', 'created_at')
    op.drop_column('recipes', 'saves_count')
    op.drop_column('recipes', 'likes_count')
    op.drop_column('recipes', 'plating_tip')
    op.drop_column('recipes', 'tags')
    op.drop_column('recipes', 'creator_name')
    op.drop_column('recipes', 'creator_handle')
    op.drop_column('recipes', 'tiktok_video_id')
    op.drop_index(op.f('ix_recipe_saves_user_id'), table_name='recipe_saves')
    op.drop_table('recipe_saves')
    # ### end Alembic commands ###
