"""initial_schema

Revision ID: cb0a44de2534
Revises: 
Create Date: 2026-03-25 09:41:27.306650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb0a44de2534'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('goal', sa.String(length=20), nullable=False),
    sa.Column('sport_days', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('diet_type', sa.String(length=20), nullable=False),
    sa.Column('cooking_time', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
